Repository SSU-GamjaDeul/triplog-backend, pull requests merged in 2025-05, with the labels that each got.

#6 [COMMON] Custom Exception 설정
  src/main/java/com/triplog/common/exception/CustomException.java
  src/main/java/com/triplog/common/exception/ErrorCode.java
  src/main/java/com/triplog/common/exception/ErrorResponse.java
  src/main/java/com/triplog/common/exception/GlobalExceptionHandler.java
  src/main/java/com/triplog/place/PlaceController.java
  src/main/java/com/triplog/place/PlaceRepository.java
  src/main/java/com/triplog/place/PlaceService.java
  src/main/java/com/triplog/place/dto/PlaceSaveRequest.java
  src/main/java/com/triplog/place/dto/PlaceSaveResponse.java
Labels: feat

#8 [USER] 회원정보 수정 API
  src/main/java/com/triplog/common/exception/ErrorCode.java
  src/main/java/com/triplog/user/controller/UserController.java
  src/main/java/com/triplog/user/domain/User.java
  src/main/java/com/triplog/user/dto/UpdateProfileRequestDto.java
  src/main/java/com/triplog/user/jwt/CustomUserDetailService.java
  src/main/java/com/triplog/user/jwt/CustomUserDetails.java
  src/main/java/com/triplog/user/jwt/JwtAuthFilter.java
  src/main/java/com/triplog/user/jwt/JwtUtil.java
  src/main/java/com/triplog/user/repository/UserRepository.java
  src/main/java/com/triplog/user/repository/UserVibeRepository.java
  src/main/java/com/triplog/user/service/UserService.java
Labels: feat

#13 [BOOKMARK] 북마크 생성/삭제
  src/main/java/com/triplog/Bookmark/controller/BookmarkController.java
  src/main/java/com/triplog/Bookmark/domain/Bookmark.java
  src/main/java/com/triplog/Bookmark/dto/BookmarkDeleteRequest.java
  src/main/java/com/triplog/Bookmark/dto/BookmarkSaveRequest.java
  src/main/java/com/triplog/Bookmark/repository/BookmarkRepository.java
  src/main/java/com/triplog/Bookmark/service/BookmarkService.java
  src/main/java/com/triplog/common/exception/ErrorCode.java
  src/main/java/com/triplog/place/PlaceFinder.java
  src/main/java/com/triplog/place/controller/PlaceController.java
  src/main/java/com/triplog/place/domain/Place.java
  src/main/java/com/triplog/place/repository/PlaceRepository.java
  src/main/java/com/triplog/place/service/PlaceService.java
  src/main/java/com/triplog/user/UserFinder.java
Labels: feat

#16 [COMMON] Swagger 설정
  build.gradle
  src/main/java/com/triplog/Bookmark/controller/BookmarkController.java
  src/main/java/com/triplog/Bookmark/dto/BookmarkDeleteRequest.java
  src/main/java/com/triplog/Bookmark/dto/BookmarkSaveRequest.java
  src/main/java/com/triplog/common/config/SwaggerConfig.java
  src/main/java/com/triplog/place/controller/PlaceController.java
  src/main/java/com/triplog/user/controller/UserController.java
  src/main/java/com/triplog/user/jwt/SecurityConfig.java
Labels: feat

#18 [RECORD] 장소 기반 기록 목록 조회
  src/main/java/com/triplog/record/controller/RecordController.java
  src/main/java/com/triplog/record/domain/Record.java
  src/main/java/com/triplog/record/domain/RecordImage.java
  src/main/java/com/triplog/record/dto/RecordFindAllByPlaceResponse.java
  src/main/java/com/triplog/record/repository/RecordRepository.java
  src/main/java/com/triplog/record/repository/RecordTagRepository.java
  src/main/java/com/triplog/record/service/RecordService.java
Labels: feat

#21 [TRIP] 여행 생성 api
  src/main/java/com/triplog/trip/TripController.java
  src/main/java/com/triplog/trip/TripService.java
  src/main/java/com/triplog/trip/dto/TripCreateRequest.java
  src/main/java/com/triplog/trip/dto/TripCreateResponse.java
  src/main/java/com/triplog/trip/repository/TripParticipantRepository.java
  src/main/java/com/triplog/trip/repository/TripRepository.java
Labels: feat

#19 [RECORD] 기록 생성
  src/main/java/com/triplog/common/exception/ErrorCode.java
  src/main/java/com/triplog/record/controller/RecordController.java
  src/main/java/com/triplog/record/domain/Record.java
  src/main/java/com/triplog/record/dto/RecordCreateDto.java
  src/main/java/com/triplog/record/service/RecordService.java
  src/main/java/com/triplog/trip/TripFinder.java
  src/main/java/com/triplog/trip/repository/TripRepository.java
  src/main/java/com/triplog/user/controller/UserController.java
Labels: feat

#22 [RECORD] 기록 수정&삭제
  src/main/java/com/triplog/common/exception/ErrorCode.java
  src/main/java/com/triplog/record/RecordFinder.java
  src/main/java/com/triplog/record/controller/RecordController.java
  src/main/java/com/triplog/record/domain/Record.java
  src/main/java/com/triplog/record/dto/RecordUpdateDto.java
  src/main/java/com/triplog/record/repository/RecordRepository.java
  src/main/java/com/triplog/record/service/RecordService.java
Labels: feat

#25 [RECORD] 위치 기반 기록 목록 조회
  src/main/java/com/triplog/place/PlaceFinder.java
  src/main/java/com/triplog/place/repository/PlaceRepository.java
  src/main/java/com/triplog/record/controller/RecordController.java
  src/main/java/com/triplog/record/domain/Record.java
  src/main/java/com/triplog/record/dto/RecordFindAllByLocationResponse.java
  src/main/java/com/triplog/record/repository/RecordRepository.java
  src/main/java/com/triplog/record/service/RecordService.java
Labels: feat

#27 [RECORD] 유저 기반 목록 조회
  src/main/java/com/triplog/record/controller/RecordController.java
  src/main/java/com/triplog/record/dto/RecordCreateDto.java
  src/main/java/com/triplog/record/dto/RecordCreateRequest.java
  src/main/java/com/triplog/record/dto/RecordFindAllByUserResponse.java
  src/main/java/com/triplog/record/dto/RecordUpdateDto.java
  src/main/java/com/triplog/record/dto/RecordUpdateRequest.java
  src/main/java/com/triplog/record/repository/RecordRepository.java
  src/main/java/com/triplog/record/repository/RecordTagRepository.java
  src/main/java/com/triplog/record/service/RecordService.java
Labels: feat

#30 [S3] 파일 업로드
  build.gradle
  src/main/java/com/triplog/common/config/S3Config.java
  src/main/java/com/triplog/place/controller/PlaceController.java
  src/main/java/com/triplog/place/domain/Place.java
  src/main/java/com/triplog/place/dto/PlaceSaveRequest.java
  src/main/java/com/triplog/place/dto/PlaceSaveResponse.java
  src/main/java/com/triplog/place/repository/PlaceRepository.java
  src/main/java/com/triplog/place/service/PlaceService.java
  src/main/java/com/triplog/s3/controller/S3Controller.java
  src/main/java/com/triplog/s3/dto/FileUploadResponse.java
  src/main/java/com/triplog/s3/service/S3Service.java
Labels: feat

#35 [BOOKMARK] 위치 기반 북마크 목록 조회
  src/main/java/com/triplog/bookmark/controller/BookmarkController.java
  src/main/java/com/triplog/bookmark/dto/BookmarkFindAllByLocationResponse.java
  src/main/java/com/triplog/bookmark/repository/BookmarkRepository.java
  src/main/java/com/triplog/bookmark/service/BookmarkService.java
Labels: feat

#39 feat: 기록 상세 조회
  src/main/java/com/triplog/record/controller/RecordController.java
  src/main/java/com/triplog/record/dto/RecordDetailResponse.java
  src/main/java/com/triplog/record/service/RecordService.java
Labels: feat

#42 [RECORD] 기록 생성, 수정, 조회에 이미지 추가
  src/main/java/com/triplog/record/dto/RecordCreateRequest.java
  src/main/java/com/triplog/record/dto/RecordDetailResponse.java
  src/main/java/com/triplog/record/dto/RecordFindAllByTripResponse.java
  src/main/java/com/triplog/record/dto/RecordUpdateRequest.java
  src/main/java/com/triplog/record/repository/RecordImageRepository.java
  src/main/java/com/triplog/record/service/RecordService.java
Labels: feat

#43 [TRIP] 여행 상세 조회 API 구현
  src/main/java/com/triplog/trip/TripController.java
  src/main/java/com/triplog/trip/TripService.java
  src/main/java/com/triplog/trip/dto/TripDetailResponse.java
Labels: feat

#45 [TRIP] 동반자 초대 API 구현
  src/main/java/com/triplog/common/exception/ErrorCode.java
  src/main/java/com/triplog/trip/TripController.java
  src/main/java/com/triplog/trip/TripService.java
  src/main/java/com/triplog/trip/domain/Trip.java
  src/main/java/com/triplog/trip/domain/TripParticipant.java
  src/main/java/com/triplog/trip/dto/TripInviteRequest.java
  src/main/java/com/triplog/trip/repository/TripParticipantRepository.java
Labels: feat

#48 [TRIP] 동반자 초대 조회 API 구현
  src/main/java/com/triplog/trip/TripController.java
  src/main/java/com/triplog/trip/TripService.java
  src/main/java/com/triplog/trip/dto/TripInviteFindByUserResponse.java
  src/main/java/com/triplog/trip/repository/TripParticipantRepository.java
Labels: feat

#50 [TRIP] 동반자 초대 수락 API 구현
  src/main/java/com/triplog/common/exception/ErrorCode.java
  src/main/java/com/triplog/trip/TripController.java
  src/main/java/com/triplog/trip/TripService.java
  src/main/java/com/triplog/trip/domain/TripParticipant.java
Labels: feat

#54 [USER] 카카오 로그인 구현
  src/main/java/com/triplog/common/exception/ErrorCode.java
  src/main/java/com/triplog/user/controller/OauthController.java
  src/main/java/com/triplog/user/controller/UserController.java
  src/main/java/com/triplog/user/domain/OauthInfo.java
  src/main/java/com/triplog/user/domain/User.java
  src/main/java/com/triplog/user/domain/enums/OauthProvider.java
  src/main/java/com/triplog/user/dto/LoginRequest.java
  src/main/java/com/triplog/user/dto/LoginRequestDto.java
  src/main/java/com/triplog/user/dto/SignupRequest.java
  src/main/java/com/triplog/user/dto/SignupRequestDto.java
  src/main/java/com/triplog/user/dto/UpdateProfileRequest.java
  src/main/java/com/triplog/user/dto/UpdateProfileRequestDto.java
  src/main/java/com/triplog/user/jwt/JwtAuthFilter.java
  src/main/java/com/triplog/user/jwt/JwtUtil.java
  src/main/java/com/triplog/user/jwt/SecurityConfig.java
  src/main/java/com/triplog/user/repository/UserRepository.java
  src/main/java/com/triplog/user/service/OauthService.java
  src/main/java/com/triplog/user/service/UserService.java
Labels: feat

#57 여행 수정&삭제 API 구현
  src/main/java/com/triplog/common/exception/ErrorCode.java
  src/main/java/com/triplog/trip/TripController.java
  src/main/java/com/triplog/trip/TripService.java
  src/main/java/com/triplog/trip/domain/Trip.java
  src/main/java/com/triplog/trip/dto/TripUpdateRequest.java
  src/main/java/com/triplog/trip/repository/TripParticipantRepository.java
  src/main/java/com/triplog/trip/repository/TripTagRepository.java
Labels: feat

#61 [TRIP] 여행 목록 조회 API 수정
  src/main/java/com/triplog/record/repository/RecordImageRepository.java
  src/main/java/com/triplog/trip/TripService.java
  src/main/java/com/triplog/trip/dto/TripFindByUserResponse.java
  src/main/java/com/triplog/trip/repository/TripParticipantRepository.java
Labels: feat

#62 [RECORD] 장소/위치 기반 기록 목록 조회 범위 확장
  src/main/java/com/triplog/bookmark/controller/BookmarkController.java
  src/main/java/com/triplog/bookmark/dto/BookmarkCheckResponse.java
  src/main/java/com/triplog/bookmark/service/BookmarkService.java
  src/main/java/com/triplog/record/controller/RecordController.java
  src/main/java/com/triplog/record/dto/RecordFindAllByPlaceResponse.java
  src/main/java/com/triplog/record/repository/RecordRepository.java
  src/main/java/com/triplog/record/service/RecordService.java
  src/main/java/com/triplog/trip/TripParticipantFinder.java
  src/main/java/com/triplog/trip/domain/Trip.java
  src/main/java/com/triplog/trip/repository/TripParticipantRepository.java
  src/main/java/com/triplog/user/jwt/SecurityConfig.java
Labels: feat, fix

#64 [USER] 회원정보 수정 시 nickname 제거
  src/main/java/com/triplog/user/domain/User.java
  src/main/java/com/triplog/user/dto/UpdateProfileRequest.java
  src/main/java/com/triplog/user/jwt/JwtUtil.java
  src/main/java/com/triplog/user/service/UserService.java
Labels: refactor
